name: Deploying
on:
  push:
      
jobs:
  deploy:
    name: Make a IPA file
    runs-on: macOS-latest
    env:
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
#       - name: Install gpg2
#         run: brew install gnupg
      - name: Setup dev provisioning profile
        run: ./.github/secrets/decrypt_secrets-dev.sh
      - name: Archiving project
        #env:
          #PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/archive_app.sh
      - name: Setup adhoc provisioning profile
#         env:
#           IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa.sh
#        if: success()
#        run: ./.github/scripts/publish_fir.sh
